import {normalizeAudio} from './normalize-audio';
import {useEffect,useRef,useState} from 'react';
import {ImageSquare,Microphone,Smiley,Gif,Star,Trash,Stop,TextT,PaperPlaneTilt,X} from '@phosphor-icons/react';
import {supabase} from '../../lib/supabase';
import {prepareMedia} from '../sharing/media';
import {favouriteGifs,saveGif,removeGif,type FavouriteGif} from './favourites';
import './composer.css';
const emoji=['😀','😂','🥹','😍','😎','🤔','😭','🙌','👏','👍','❤️','🔥','✨','🎉','🎶','☕','👀','💯','🙏','🌿','😊','🤝','💪','🎂'];
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((e:{resultIndex:number;results:{length:number;[key:number]:{isFinal:boolean;0:{transcript:string}}}})=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
type SpeechWindow=Window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
function BlobPreview({blob,name}:{blob:Blob;name:string}){const [url,setUrl]=useState('');useEffect(()=>{const value=URL.createObjectURL(blob);setUrl(value);return()=>URL.revokeObjectURL(value);},[blob]);return blob.type.startsWith('audio/')?<audio src={url} controls aria-label="Voice message preview"/>:<img src={url} alt={name}/>;}
export function ComposerTools({groupId,userId,draft,onDraft,onSent,onSendReady}:{groupId:string;userId:string;draft:string;onDraft:(text:string)=>void;onSent:()=>void;onSendReady:(handler:(()=>Promise<void>)|null,busy:boolean)=>void}){
 const [panel,setPanel]=useState<'emoji'|'gif'|'voice'|null>(null),[file,setFile]=useState<File|null>(null),[prepared,setPrepared]=useState<Blob|null>(null),[error,setError]=useState(''),[status,setStatus]=useState(''),[saved,setSaved]=useState(false),[recording,setRecording]=useState(false),[dictating,setDictating]=useState(false),[seconds,setSeconds]=useState(0),[favourites,setFavourites]=useState<FavouriteGif[]>([]);
 const input=useRef<HTMLInputElement>(null),gifInput=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),speech=useRef<Recognition|null>(null),alive=useRef(true),discard=useRef(false),reservation=useRef<string|null>(null),latestDraft=useRef(draft),operation=useRef(false);
 latestDraft.current=draft;const busy=!!status;
 useEffect(()=>{onSendReady(prepared?send:null,busy);},[prepared,draft,busy]);
 useEffect(()=>()=>onSendReady(null,false),[]);
 useEffect(()=>{alive.current=true;const hidden=()=>{if(document.hidden)speech.current?.stop();};document.addEventListener('visibilitychange',hidden);return()=>{document.removeEventListener('visibilitychange',hidden);alive.current=false;discard.current=true;recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());speech.current?.abort();};},[]);
 useEffect(()=>{if(!recording)return;const started=Date.now();const timer=setInterval(()=>{const elapsed=Math.floor((Date.now()-started)/1000);setSeconds(elapsed);if(elapsed>=119)recorder.current?.stop();},250);const hidden=()=>{if(document.hidden&&recorder.current?.state==='recording')recorder.current.stop();};document.addEventListener('visibilitychange',hidden);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',hidden);};},[recording]);
 async function pick(value:File){if(operation.current||reservation.current)return;operation.current=true;setStatus('Preparing attachment…');setError('');try{const blob=value.type.startsWith('audio/')?await normalizeAudio(value):await prepareMedia(value);if(alive.current){setFile(value);setPrepared(blob);setSaved(false);setPanel(null);}}catch(e){if(alive.current)setError((e as Error).message);}finally{operation.current=false;if(alive.current)setStatus('');}}
 async function library(){setStatus('Loading favourite GIFs…');setPanel(panel==='gif'?null:'gif');setError('');try{setFavourites(await favouriteGifs(userId));}catch(e){setError((e as Error).message);}finally{setStatus('');}}
 async function send(){if(!prepared||operation.current)return;operation.current=true;setStatus('Preparing upload…');setError('');try{
  let done=false;
  if(reservation.current){const existing=await supabase!.rpc('publish_media',{p_content_id:reservation.current});if(!existing.error)done=true;else if(!existing.error.message.includes('UPLOAD_MISSING'))throw existing.error;}
  if(!done){if(!reservation.current){const result=await supabase!.rpc('reserve_media',{p_group_id:groupId,p_kind:'chat',p_caption:draft.trim()||(prepared.type.startsWith('audio/')?'Voice message':''),p_mime:prepared.type.split(';')[0],p_bytes:prepared.size});if(result.error)throw result.error;reservation.current=result.data.id;}
   setStatus('Uploading attachment…');const form=new FormData();form.set('contentId',reservation.current!);form.set('file',new Blob([prepared],{type:prepared.type.split(';')[0]}),'attachment');const upload=await supabase!.functions.invoke('upload-media',{body:form});if(upload.error)throw upload.error;
   setStatus('Sending to group…');const result=await supabase!.rpc('publish_media',{p_content_id:reservation.current});if(result.error)throw result.error;
  }
  reservation.current=null;if(alive.current){setFile(null);setPrepared(null);if(latestDraft.current===draft)onDraft('');onSent();}
 }catch{if(alive.current)setError('Could not confirm sending. Retry to check and finish the same upload without duplicating it.');}finally{operation.current=false;if(alive.current)setStatus('');}}
 async function record(){if(operation.current||recording||dictating)return;operation.current=true;setStatus('Waiting for microphone…');setError('');discard.current=false;try{
  if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Voice recording is unavailable in this browser.');
  const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;
  const mime=['audio/webm;codecs=opus','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('This browser cannot record a supported audio format.');
  const chunks:Blob[]=[];let bytes=0;const rec=new MediaRecorder(media,{mimeType:mime,audioBitsPerSecond:64000});recorder.current=rec;
  rec.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);bytes+=e.data.size;if(bytes>5242880&&rec.state==='recording')rec.stop();}};
  rec.onerror=()=>{discard.current=true;setError('Recording interrupted. Please try again.');rec.state==='recording'&&rec.stop();};
  rec.onstop=()=>{media.getTracks().forEach(t=>t.stop());if(!alive.current)return;setRecording(false);if(discard.current)return;if(!bytes||bytes>5242880){setError('Recording could not be saved. Try a shorter message.');return;}void pick(new File(chunks,'Voice message.'+(mime.includes('mp4')?'m4a':'webm'),{type:mime.split(';')[0]}));};
  setSeconds(0);setRecording(true);rec.start(250);
 }catch(e){stream.current?.getTracks().forEach(t=>t.stop());if(alive.current)setError((e as Error).message);}finally{operation.current=false;if(alive.current)setStatus('');}}
 function dictate(){if(dictating){speech.current?.stop();return;}const Constructor=(window as SpeechWindow).SpeechRecognition||(window as SpeechWindow).webkitSpeechRecognition;if(!Constructor){setError('Speech-to-text is not supported here. You can use your device keyboard dictation or record a voice message.');return;}
  const recognition=new Constructor();speech.current=recognition;recognition.lang=navigator.language;recognition.continuous=true;recognition.interimResults=false;recognition.onresult=e=>{if(!alive.current)return;let text='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)text+=e.results[i][0].transcript+' ';onDraft((latestDraft.current+' '+text).trim().slice(0,4000));};recognition.onerror=e=>{if(alive.current){setError('Dictation stopped ('+e.error+'). Your draft is kept.');setDictating(false);}};recognition.onend=()=>{if(alive.current)setDictating(false);};try{recognition.start();setError('');setDictating(true);}catch{setError('Could not start dictation. Check microphone permission.');}}
 return <div className="composer-tools" aria-busy={busy} data-recording={recording||dictating}>
 <input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp" aria-label="Attach image file" onChange={e=>{const value=e.target.files?.[0];e.target.value='';if(value)void pick(value);}}/>
 <input ref={gifInput} hidden type="file" accept="image/gif" aria-label="Attach GIF file" onChange={e=>{const value=e.target.files?.[0];e.target.value='';if(value)void pick(value);}}/>
 <div className="composer-tool-row" role="group" aria-label="Message tools">
 <button type="button" aria-label="Attach image" disabled={busy||recording||!!reservation.current} onClick={()=>input.current?.click()}><ImageSquare size={20}/></button>
 <button type="button" aria-label="Voice input" aria-expanded={panel==='voice'} disabled={busy||!!reservation.current} onClick={()=>setPanel(panel==='voice'?null:'voice')}><Microphone size={20}/></button>
 <button type="button" aria-label="Choose emoji" aria-expanded={panel==='emoji'} disabled={busy} onClick={()=>setPanel(panel==='emoji'?null:'emoji')}><Smiley size={20}/></button>
 <button type="button" aria-label="Choose GIF" aria-expanded={panel==='gif'} disabled={busy||recording||!!reservation.current} onClick={()=>void library()}><Gif size={23}/></button>
 <span>{recording?`Recording ${seconds}s / 120s`:dictating?'Listening for your words…':'Make it a little more you.'}</span>
 </div>
 {panel==='emoji'&&<div className="expression-panel"><div className="expression-heading"><strong>A little expression</strong><button type="button" aria-label="Close emoji picker" onClick={()=>setPanel(null)}><X/></button></div><div className="emoji-grid">{emoji.map(value=><button type="button" key={value} aria-label={'Add '+value} onClick={()=>{onDraft((draft+value).slice(0,4000));setPanel(null);document.querySelector<HTMLInputElement>('.composer input')?.focus();}}>{value}</button>)}</div></div>}
 {panel==='voice'&&<div className="expression-panel"><strong>Your voice, your way.</strong><p>Voice messages stay in this group. Dictation may send audio to your browser’s speech service; review the text before sending.</p><div className="voice-input-actions"><button type="button" disabled={busy||dictating||!!prepared} onClick={()=>recording?recorder.current?.stop():void record()}>{recording?<Stop/>:<Microphone/>}{recording?'Stop & preview':'Record voice message'}</button><button type="button" disabled={busy||recording} onClick={dictate}><TextT/>{dictating?'Stop dictation':'Start dictation'}</button>{recording&&<button type="button" onClick={()=>{discard.current=true;recorder.current?.stop();}}>Discard recording</button>}</div></div>}
 {panel==='gif'&&<div className="expression-panel"><div className="expression-heading"><strong>Your GIF collection</strong><button type="button" onClick={()=>gifInput.current?.click()}>Upload GIF</button></div><p>Animated GIFs up to 2 MB. Favourites are saved on this device for your account.</p><div className="gif-grid">{favourites.map(g=><div key={g.id}><button type="button" aria-label={'Use GIF '+g.name} onClick={()=>void pick(new File([g.blob],g.name,{type:'image/gif'}))}><BlobPreview blob={g.blob} name={g.name}/></button><button type="button" aria-label={'Remove favourite '+g.name} disabled={busy} onClick={()=>{setStatus('Removing favourite…');void removeGif(userId,g.id).then(()=>favouriteGifs(userId)).then(setFavourites).catch(e=>setError(e.message)).finally(()=>setStatus(''));}}><Trash size={16}/></button></div>)}</div>{!favourites.length&&<p>No favourites yet. Upload a GIF and tap Save favourite before sending.</p>}</div>}
 {prepared&&file&&<div className="attachment-preview"><BlobPreview blob={prepared} name={file.name}/><div><strong>{prepared.type.startsWith('audio/')?'Voice message':file.name}</strong><small>{Math.ceil(prepared.size/1024)} KB · only this group</small><div className="attachment-actions">{prepared.type==='image/gif'&&<button type="button" disabled={busy||saved} onClick={()=>{setStatus('Saving favourite…');void saveGif(userId,file.name,prepared).then(()=>{setError('');setSaved(true);}).catch(e=>setError(e.message)).finally(()=>setStatus(''));}}><Star/>{saved?'Saved to favourites':'Save favourite'}</button>}<button type="button" disabled={busy} onClick={()=>void send()}><PaperPlaneTilt/>{reservation.current?'Retry attachment':'Send attachment'}</button><button type="button" disabled={busy||!!reservation.current} onClick={()=>{setFile(null);setPrepared(null);setError('');}}><X/>Discard</button></div></div></div>}
 {busy&&<p role="status" className="composer-progress"><span className="wait-orbit"/>{status}</p>}{error&&<p role="alert" className="auth-error">{error}</p>}
 </div>;
}
