import { useEffect,useRef,useState } from 'react';
import { Sparkle, X } from '@phosphor-icons/react';
import { supabase } from '../../lib/supabase';
import { Sheet } from '../groups/Sheet';
import './ai.css';
type Job={id:string;kind:string;state:string;result:string;sources:string[];partial:boolean;created_at:string};
export function AIPanel({groupId,owner}:{groupId:string;owner:boolean}){
 const [enabled,setEnabled]=useState(false),[jobs,setJobs]=useState<Job[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(false),[source,setSource]=useState<string|null>(null),[loading,setLoading]=useState(true);
 const [period,setPeriod]=useState('7'),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const alive=useRef(true),requestId=useRef<{key:string;id:string;start:string;end:string}|null>(null);
 async function load(){const [g,j]=await Promise.all([supabase!.from('groups').select('ai_enabled').eq('id',groupId).single(),supabase!.from('ai_jobs').select('id,kind,state,result,sources,partial,created_at').eq('group_id',groupId).neq('kind','song').order('created_at',{ascending:false}).limit(30)]);if(g.error||j.error)throw g.error||j.error;if(alive.current){setEnabled(g.data.ai_enabled);setJobs(j.data||[]);setLoading(false);}}
 useEffect(()=>{alive.current=true;const refresh=()=>{if(!document.hidden)void load().catch(()=>{if(alive.current){setError('Could not load group AI.');setLoading(false);}});};refresh();const timer=setInterval(refresh,10000);return()=>{alive.current=false;clearInterval(timer);};},[groupId]);
 async function toggle(value:boolean){setBusy(true);setError('');const r=await supabase!.rpc('set_group_ai',{p_group_id:groupId,p_enabled:value});if(r.error)setError('Only the current owner can change group AI.');else{setConsent(false);await load();}setBusy(false);}
 async function ask(kind:string){if(busy)return;setBusy(true);setError('');try{
 const key=[kind,period,from,to].join('|');if(requestId.current?.key!==key){const now=new Date(),start=period==='custom'?new Date(from+'T00:00:00'):new Date(now.getTime()-Number(period)*86400000);let end=now;if(period==='custom'){end=new Date(to+'T00:00:00');end.setDate(end.getDate()+1);if(end>now)end=now;}
 if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||start>=end||end.getTime()-start.getTime()>31*86400000)throw Error('Choose a valid conversation range of up to 31 days.');requestId.current={key,id:crypto.randomUUID(),start:start.toISOString(),end:end.toISOString()};}
 const r=await supabase!.functions.invoke('group-ai',{body:{groupId,kind,clientId:requestId.current.id,rangeStart:requestId.current.start,rangeEnd:requestId.current.end}});if(r.error){const detail=await r.error.context?.json?.().catch(()=>null);throw Error(detail?.error||'AI is unavailable. Try again later.');}requestId.current=null;await load();}catch(e){setError(e instanceof Error?e.message:'AI is unavailable.');}finally{setBusy(false);}}
 async function openSource(id:string){const r=await supabase!.from('group_messages').select('body,created_at').eq('group_id',groupId).eq('id',id).is('deleted_at',null).maybeSingle();setSource(r.error||!r.data?'This source message was deleted or is no longer available.':`${new Date(r.data.created_at).toLocaleString()}\n\n${r.data.body}`);}
 return <section className="ai-panel"><header><Sparkle size={30}/><h2>A little help catching up.</h2><p>Summaries, decisions and draft notes, when you ask.</p></header><div className="ai-disclosure"><strong>{enabled?'Group AI is enabled':'Group AI is off'}</strong><p>OpenRouter and its model provider process selected group text. Temporary chats are never included. When enabled, one automatic summary covers the previous week after Monday 9:00 AM in this group’s timezone.</p>{owner&&<button className="text-button" disabled={busy||loading} onClick={()=>enabled?void toggle(false):setConsent(true)}>{enabled?'Turn off group AI':'Enable group AI'}</button>}</div>{error&&<p className="auth-error" role="alert">{error}</p>}<div className="ai-range"><label>Conversation range<select aria-label="Conversation range" disabled={busy} value={period} onChange={e=>setPeriod(e.target.value)}><option value="1">Past 24 hours</option><option value="7">Past 7 days</option><option value="30">Past 30 days</option><option value="custom">Choose dates</option></select></label>{period==='custom'&&<><label>From date<input aria-label="From date" type="date" disabled={busy} value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through date<input aria-label="Through date" type="date" disabled={busy} value={to} onChange={e=>setTo(e.target.value)}/></label><small>Dates use this device’s timezone. Today ends at the moment you request a summary.</small></>}</div><div className="ai-actions">{[['summary','Catch me up'],['decisions','Find decisions'],['notes','Draft notes & tasks']].map(([kind,label])=><button key={kind} disabled={!enabled||busy||loading} onClick={()=>void ask(kind)}>{label}</button>)}</div><p className="ai-limits">Latest messages within your selected range and the context limit. Up to 3 requests per person/day and 20 requested runs/day across this pilot. Free-model availability varies.</p>{busy&&<p role="status">Working on your request…</p>}<h3>Group notebook</h3>{!jobs.length?<p className="ai-empty">Requested results and weekly summaries will appear here.</p>:jobs.map(j=><article className="ai-result" key={j.id}><header><strong>{({summary:'Catch-up summary',decisions:'Decisions',notes:'Draft notes',weekly:'Weekly summary'} as Record<string,string>)[j.kind]}</strong><span>{j.state} · {new Date(j.created_at).toLocaleDateString()}</span></header><p>{j.result||'Waiting for a result…'}</p>{j.partial&&<small>Partial coverage: the conversation exceeded the input limit.</small>}{j.state==='done'&&<details><summary>Source messages ({j.sources.length})</summary><div className="ai-sources">{j.sources.map((id,i)=><button key={id} onClick={()=>void openSource(id)}>Message {i+1}</button>)}</div></details>}</article>)}
 {consent&&<Sheet label="Enable group AI" onClose={()=>setConsent(false)}><h2>Enable AI for this group?</h2><p>Selected group messages will be sent to OpenRouter and a free model provider when a member asks, and once each week for a summary. Tell your members before enabling. AI may make mistakes and never changes group permissions or takes actions.</p><button className="primary-button" disabled={busy} onClick={()=>void toggle(true)}>Enable group AI</button><button className="text-button" onClick={()=>setConsent(false)}>Keep AI off</button></Sheet>}
 {source!==null&&<Sheet label="Summary source message" onClose={()=>setSource(null)}><button className="modal-close icon-btn" aria-label="Close source message" onClick={()=>setSource(null)}><X/></button><h2>Source message</h2><p className="ai-source-text">{source}</p></Sheet>}
 </section>;
}
