import {useEffect,useRef,useState} from 'react';
import {supabase} from '../../lib/supabase';
type Saved={id:string;name:string;created_by:string;tracks:unknown[]};
export function MusicLibrary({groupId,userId,onLoaded}:{groupId:string;userId:string;onLoaded:()=>void}){
 const [items,setItems]=useState<Saved[]>([]),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef<{id:string;action:string;target:string}|null>(null);
 async function refresh(){const r=await supabase!.from('music_saved_queues').select('id,name,created_by,tracks').eq('group_id',groupId).order('created_at');if(r.error)throw r.error;setItems(r.data||[]);}
 useEffect(()=>{void refresh().catch(()=>setError('Could not load saved queues. Reopen the music box to retry.'));},[groupId]);
 async function act(action:string,id=''){if(busy)return;setBusy(true);setError('');const target=action==='save'?name.trim():id;if(!request.current||request.current.action!==action||request.current.target!==target)request.current={id:crypto.randomUUID(),action,target};try{const r=action==='load'?await supabase!.rpc('load_music_queue',{p_group_id:groupId,p_saved_id:id,p_request_id:request.current.id}):await supabase!.rpc('music_library',{p_group_id:groupId,p_action:action,p_name:target,p_id:action==='save'?request.current.id:id});if(r.error)throw r.error;request.current=null;if(action==='save')setName('');await refresh();onLoaded();}catch{setError('Could not update the library. Join listening before loading a queue; keep up to 10 saved queues and 100 queued tracks. Retry if your connection dropped.');}finally{setBusy(false);}}
 return <details className="music-library"><summary>Saved group playlists</summary><p>Keep a queue for another day. Loading adds its songs to the current queue.</p><form onSubmit={e=>{e.preventDefault();void act('save');}}><label>Playlist name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="Late-night study mix"/></label><button disabled={busy||!name.trim()}>Save current queue</button></form>{busy&&<p role="status">Updating saved playlists…</p>}{error&&<p role="alert">{error}</p>}{items.map(item=><div key={item.id}><span>{item.name} · {item.tracks.length} tracks</span><button disabled={busy} onClick={()=>void act('load',item.id)}>Load</button>{item.created_by===userId&&<button disabled={busy} onClick={()=>void act('delete',item.id)}>Delete saved playlist</button>}</div>)}</details>;
}
export function MusicReactions({itemId,userId}:{itemId:string;userId:string}){
 const [items,setItems]=useState<{user_id:string;reaction:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;const load=async()=>{const r=await supabase!.from('music_reactions').select('user_id,reaction').eq('item_id',itemId);if(live&&!r.error)setItems(r.data||[]);};void load();const timer=setInterval(()=>void load(),10000);return()=>{live=false;clearInterval(timer);};},[itemId]);
 async function react(reaction:string){if(busy)return;setBusy(true);setError('');try{const r=await supabase!.rpc('set_music_reaction',{p_item_id:itemId,p_reaction:reaction});if(r.error)throw r.error;setItems(old=>[...old.filter(i=>i.user_id!==userId),{user_id:userId,reaction}]);}catch{setError('Reaction not saved. Try again.');}finally{setBusy(false);}}
 return <div className="music-reactions" aria-label="Song reactions">{[['love','❤️'],['fire','🔥'],['applause','👏']].map(([value,label])=><button key={value} disabled={busy} aria-label={'React '+value} aria-pressed={items.some(i=>i.user_id===userId&&i.reaction===value)} onClick={()=>void react(value)}>{label} {items.filter(i=>i.reaction===value).length}</button>)}{busy&&<span role="status">Saving…</span>}{error&&<span role="alert">{error}</span>}</div>;
}
