import {MusicLibrary,MusicReactions} from './MusicLibrary';
import {createPortal} from 'react-dom';
import {YouTubePlaylistPlayer} from './YouTubePlaylistPlayer';
import {useEffect,useRef,useState} from 'react';
import {MusicNotes,Headphones,ArrowUp,ArrowDown} from '@phosphor-icons/react';
import {supabase} from '../../lib/supabase';
import {parseMusicLink,providerURL} from './links';
import type {MusicLink} from './links';
import {YouTubePlayer} from './YouTubePlayer';
import {SongSearch} from './SongSearch';
import {RoomPopover} from '../groups/RoomPopover';
import './music.css';
type QueueItem=MusicLink&{id:string;title:string;added_by?:string};
type State={session:{host_id:string;current_id:string|null;playing:boolean;position:number;revision:number;playlist_index?:number;playlist_video_id?:string|null;updated_at:string}|null;queue:QueueItem[];listeners:{user_id:string;name:string}[];votes:number;voted:boolean;server_time:string};
export function MusicRoom({groupId,userId,dockTarget,names={}}:{groupId:string;userId:string;dockTarget?:HTMLElement|null;names?:Record<string,string>}){
 const [providerLoaded,setProviderLoaded]=useState(false);
 const [open,setOpen]=useState(false),[state,setState]=useState<State|null>(null),[joined,setJoined]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[link,setLink]=useState(''),[title,setTitle]=useState(''),[preview,setPreview]=useState<MusicLink|null>(null),[seek,setSeek]=useState('0');
 const recoveryKey='apu-listening:'+userId+':'+groupId;
 const [rejoin,setRejoin]=useState(()=>{try{return sessionStorage.getItem(recoveryKey)||'';}catch{return '';}});
 function remember(value:string){setRejoin(value);try{value?sessionStorage.setItem(recoveryKey,value):sessionStorage.removeItem(recoveryKey);}catch{/* Playback does not require storage. */}}
 const connection=useRef(crypto.randomUUID()),alive=useRef(true),isJoined=useRef(false),sequence=useRef(0);
 const current=state?.queue.find(q=>q.id===state.session?.current_id),host=state?.session?.host_id===userId,synced=current?.provider==='youtube';
 useEffect(()=>setProviderLoaded(false),[current?.id]);
 function stop(){isJoined.current=false;setJoined(false);}
 function accept(data:State){setState(data);if(isJoined.current&&!data.listeners.some(l=>l.user_id===userId)){stop();setError('Your listening session ended. Join again to resume.');}}
 async function action(action:string,payload:Record<string,unknown>={}){setBusy(true);setError('');const version=++sequence.current;try{const r=action==='join'&&rejoin?await supabase!.rpc('resume_music',{p_group_id:groupId,p_previous:rejoin,p_connection:connection.current}):await supabase!.rpc('music_action',{p_group_id:groupId,p_action:action,p_payload:{revision:state?.session?.revision,connection:connection.current,...payload}});if(r.error)throw r.error;if(!alive.current)return;if(action==='join'){isJoined.current=true;setJoined(true);remember(connection.current);}if(action==='leave'){stop();remember('');}if(version===sequence.current)accept(r.data);if(action==='add'){setLink('');setTitle('');setPreview(null);}return version===sequence.current;}catch(e){if(alive.current){const message=typeof e==='object'&&e&&'message'in e?String(e.message):'Connection unavailable';setError(message==='ALREADY_LISTENING'?'You are already listening in another tab. Leave there first.':message==='STALE_REVISION'?'The host changed the session. Refreshing—please try again.':message==='HOST_ONLY'?'Only the current host can do that.':message==='JOIN_LISTENING_FIRST'?'Join listening to start the music box.':message);}return false;}finally{if(alive.current)setBusy(false);}}
 useEffect(()=>{alive.current=true;const id=connection.current;async function refresh(){const version=++sequence.current;const r=isJoined.current?await supabase!.rpc('music_action',{p_group_id:groupId,p_action:'heartbeat',p_payload:{connection:id}}):await supabase!.rpc('music_state',{p_group_id:groupId});if(!alive.current||version!==sequence.current)return;if(r.error){stop();setState(null);setError('Could not refresh music. Join again when connected.');}else accept(r.data);}
 void refresh();const timer=setInterval(()=>void refresh(),15000);window.addEventListener('focus',refresh);return()=>{alive.current=false;clearInterval(timer);window.removeEventListener('focus',refresh);if(isJoined.current)void supabase!.rpc('music_action',{p_group_id:groupId,p_action:'leave',p_payload:{connection:id}});isJoined.current=false;};},[groupId,userId]);
 useEffect(()=>{if(!open&&!joined)return;let live=true;const timer=setInterval(async()=>{if(busy)return;const version=++sequence.current;const r=await supabase!.rpc('music_state',{p_group_id:groupId});if(live&&alive.current&&version===sequence.current){if(r.error){stop();setState(null);setError('Music connection interrupted. Join again to retry.');}else accept(r.data);}},3000);return()=>{live=false;clearInterval(timer);};},[open,joined,busy,groupId]);
 return <section className="music-room"><button className="music-toggle" aria-label="Music box" title="Music box" aria-expanded={open} onClick={()=>setOpen(!open)}><MusicNotes size={18}/><span>Music box</span><small>{joined?'Listening · ':''}{state?.listeners.length||0} {state?.listeners.length===1?'listener':'listeners'}</small></button>{open&&<RoomPopover className="music-body" label="Music box" onClose={()=>setOpen(false)}><header><div><h2>Your room. Your soundtrack.</h2><p>Your group’s soundtrack. Minimize this panel to keep listening while you chat.</p></div><button className="primary-button" disabled={busy} onClick={()=>void action(joined?'leave':'join')}><Headphones/>{joined?'Leave listening':rejoin?'Rejoin listening':'Join listening'}</button></header><div className="music-room-scene"><div className={'room-record '+(joined?'record-arrive':'')} aria-hidden="true"><i/><span><MusicNotes size={24}/></span></div><div><h3>{current?.title||'Good company, good music.'}</h3><p>{joined?`${state?.listeners.length||0} listening together`:'Bring a song. Find your people.'}</p><span className="music-provider-tags">YouTube · Spotify · Apple Music</span></div></div>{!joined&&rejoin&&<p className="music-note">Welcome back. Rejoin here to replace your previous listening session. Audio starts only after you choose to join.</p>}{busy&&<p role="status" className="music-note">Updating listening session…</p>}{error&&<p className="auth-error" role="alert">{error}</p>}
 {current&&<div className="music-now"><strong>{current.title}</strong><a href={providerURL(current)} target="_blank" rel="noreferrer">Open on {current.provider==='youtube'?'YouTube':current.provider==='apple'?'Apple Music':'Spotify'}</a></div>}

 {current&&<p className="music-note">{current.provider==='spotify'?'Spotify playback opens in Spotify. Your group shares the queue and skip votes; playback is individual.':synced?'Host controls below coordinate YouTube playback. Buffering and ads can affect timing; video-player controls are local.':'This provider player handles playback individually. The shared queue and skip votes work, but playback is not synchronized.'}</p>}
 {joined&&state?.session&&<div className="music-session-controls">{host&&<>{synced&&<><button disabled={busy} onClick={()=>void action(state.session!.playing?'pause':'play')}>{state.session.playing?'Pause for group':'Play for group'}</button><label>Seek seconds<input type="number" min="0" max="86400" value={seek} onChange={e=>setSeek(e.target.value)}/></label><button disabled={busy||!Number.isFinite(Number(seek))} onClick={()=>void action('seek',{position:Number(seek)})}>Seek</button></>}<button disabled={busy||!current} onClick={()=>void action('next')}>Next item</button></>}{current&&<button disabled={busy||state.voted} onClick={()=>void action('skip',{track:current.id})}>{state.voted?'Voted to skip':'Vote to skip'} · {state.votes}/{Math.floor(state.listeners.length/2)+1}</button>}</div>}
 {current&&<MusicReactions key={current.id} itemId={current.id} userId={userId}/>}
 <form className="music-add" onSubmit={e=>{e.preventDefault();try{setPreview(parseMusicLink(link));setError('');}catch(err){setPreview(null);setError((err as Error).message);}}}><label>Song or playlist link<input type="url" required value={link} onChange={e=>{setLink(e.target.value);setPreview(null);}} placeholder="YouTube, Spotify or Apple Music"/></label><button disabled={busy}>Check link</button>{preview&&<div className="music-link-preview"><p>{preview.provider} · {preview.kind} · {preview.external_id}</p><label>Queue label<input value={title} maxLength={160} onChange={e=>setTitle(e.target.value)} placeholder="Song or playlist name"/></label><button type="button" disabled={busy||!state?.session} onClick={()=>void action('add',{...preview,title})}>Add to this group’s queue</button></div>}</form>
 <SongSearch groupId={groupId} canAdd={!!state?.session} busy={busy} onAdd={async m=>{await action('add',{...m,title:(m.title+' — '+m.artist).slice(0,160)});}}/><h3 className="music-queue-heading">Up next <span>{state?.queue.length||0} in queue</span></h3><ol className="music-queue">{state?.queue.map(item=><li className={item.id===state.session?.current_id?'current-track':''} key={item.id}><span className="queue-number" aria-hidden="true">{String((state?.queue.indexOf(item)||0)+1).padStart(2,'0')}</span><span className="queue-track">{item.id===state.session?.current_id?'Now · ':''}{item.title}<small>{item.provider} · {item.kind} · added by {item.added_by===userId?'you':names[item.added_by||'']||'a member'}</small></span>{host&&item.id!==state.session?.current_id&&<><button aria-label={'Move '+item.title+' up'} disabled={busy} onClick={()=>void action('move',{item_id:item.id,direction:'up'})}><ArrowUp/></button><button aria-label={'Move '+item.title+' down'} disabled={busy} onClick={()=>void action('move',{item_id:item.id,direction:'down'})}><ArrowDown/></button></>}</li>)}</ol>
 {!!state?.listeners.length&&<div className="music-listeners"><h3>Listening together</h3>{state.listeners.map(l=><div key={l.user_id}><span>{l.name}{l.user_id===state.session?.host_id?' · Host':''}</span>{host&&l.user_id!==userId&&<button disabled={busy} onClick={()=>void action('transfer',{user_id:l.user_id})}>Make host</button>}</div>)}</div>}
 <MusicLibrary groupId={groupId} userId={userId} onLoaded={()=>window.dispatchEvent(new Event('focus'))}/></RoomPopover>}
 {(joined||rejoin)&&dockTarget&&createPortal(<section className="music-dock" aria-label="Listening session"><div className="music-dock-top"><span className="dock-record" aria-hidden="true"><MusicNotes size={17}/></span><button className="music-dock-title" onClick={()=>setOpen(true)}><strong>{current?.title||'Your queue is ready'}</strong><small>{!joined?'Your previous session · tap Rejoin to resume':`${state?.listeners.length||0} listening · ${host?'You are the host':'Following the host'} · ${current?.provider==='spotify'?'Open in Spotify':state?.session?.playing?'Playing':'Ready to play'}`}</small></button><button disabled={busy} onClick={()=>setOpen(true)}>Queue</button><button disabled={busy} onClick={()=>void action(joined?'leave':'join')}>{joined?'Leave':'Rejoin'}</button></div> {joined&&current?.provider==='apple'&&!providerLoaded&&<p role="status" className="music-note">Loading Apple Music player…</p>}
 {joined&&current&&current.provider!=='spotify'&&(current.provider==='youtube'&&current.kind==='playlist'?<YouTubePlaylistPlayer key={current.id} playlistId={current.external_id} videoId={state?.session?.playlist_video_id||null} playlistIndex={state?.session?.playlist_index||0} host={host} playing={!!state?.session?.playing} position={state?.session?.position||0} updatedAt={state!.session!.updated_at} serverTime={state!.server_time} onTrack={async selection=>!!await action('playlist_track',{...selection,item_id:current.id})} onComplete={async()=>!!await action('next')}/>:current.provider==='youtube'?<YouTubePlayer key={current.id} host={host} onComplete={async()=>!!await action('next')} videoId={current.external_id} playing={!!state?.session?.playing} position={state?.session?.position||0} updatedAt={state!.session!.updated_at} serverTime={state!.server_time}/>:<iframe key={current.id} onLoad={()=>setProviderLoaded(true)} className="music-provider" title={current.provider+' '+current.kind} src={providerURL(current).replace('music.apple.com','embed.music.apple.com')} allow="autoplay; encrypted-media; fullscreen; picture-in-picture" referrerPolicy="strict-origin-when-cross-origin"/>)}{current?.provider==='spotify'&&<a className="music-dock-link" href={providerURL(current)} target="_blank" rel="noreferrer">Open in Spotify</a>}{busy&&<p role="status" className="music-note">Updating listening session…</p>}{error&&<p role="alert" className="music-note">{error}</p>}</section>,dockTarget)}
</section>;
}
