import {useRef,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {providerURL} from './links';
import type {MusicLink} from './links';
type Match=MusicLink&{title:string;artist:string;album:string};
export function SongSearch({groupId,canAdd,busy,onAdd}:{groupId:string;canAdd:boolean;busy:boolean;onAdd:(track:Match)=>Promise<void>}){
 const [query,setQuery]=useState(''),[country,setCountry]=useState('MY'),[searching,setSearching]=useState(false),[matches,setMatches]=useState<Match[]>([]),[terms,setTerms]=useState(''),[error,setError]=useState(''),[searched,setSearched]=useState(false);
 const request=useRef<{key:string;id:string}|null>(null);
 async function search(e:React.FormEvent){e.preventDefault();if(searching||!query.trim())return;const key=country+':'+query.trim();if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};setSearching(true);setError('');setMatches([]);setSearched(false);
  try{const r=await supabase!.functions.invoke('find-song',{body:{groupId,query:query.trim(),country,clientId:request.current.id}});if(r.error){const detail=await r.error.context?.json?.().catch(()=>null);throw Error(detail?.error||'Song search could not connect. Try the same search again.');}if(r.data.state==='done'){setMatches(r.data.matches||[]);setTerms(r.data.query);setSearched(true);request.current=null;}else{if(r.data.state==='failed')request.current=null;throw Error(r.data.error||'Song search is still running.');}}catch(e){setError(e instanceof Error?e.message:'Song search unavailable.');}finally{setSearching(false);}
 }
 return <section className="song-search"><h3>Find a song</h3><p>Know the title, artist, or just a description? Review the matches before adding one.</p><form onSubmit={search}><label>Song description<input value={query} maxLength={500} required disabled={searching} onChange={e=>setQuery(e.target.value)} placeholder="The Daft Punk song with Pharrell"/></label><label>Catalog region<select value={country} disabled={searching} onChange={e=>setCountry(e.target.value)}>{[['MY','Malaysia'],['US','United States'],['GB','United Kingdom'],['AU','Australia'],['SG','Singapore'],['IN','India']].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><button disabled={searching||!query.trim()}>{searching?'Finding matches…':'Find matches'}</button></form><small>Requires group AI. OpenRouter receives your description; Apple receives the search terms. Uses your shared AI request allowance. Apple controls playback: previews may be limited to 30 seconds without an eligible signed-in account. Playback is individual.</small>{error&&<p role="alert" className="auth-error">{error}</p>}{searched&&<><p role="status">{matches.length?`Matches for “${terms}”`:'No matches found. Try a title or artist, or paste a music link.'}</p><ul>{matches.map(m=><li key={m.external_id}><div><strong>{m.title}</strong><span>{m.artist}</span><small>{m.album}</small></div><a href={providerURL(m)} target="_blank" rel="noreferrer">Check on Apple Music</a><button disabled={busy||!canAdd} aria-label={`Add ${m.title} by ${m.artist}`} onClick={()=>void onAdd(m)}>Add to queue</button></li>)}</ul>{!canAdd&&!!matches.length&&<p>Join listening to start a queue before adding a match.</p>}</>}</section>;
}
