import {useEffect,useRef,useState} from 'react';
import {Microphone,MicrophoneSlash,PhoneDisconnect} from '@phosphor-icons/react';
import {VoiceConnection} from './connection';
import type {VoiceMember} from './connection';
import {RoomPopover} from '../groups/RoomPopover';
import './voice.css';
function RemoteAudio({stream,name}:{stream:MediaStream;name:string}){const ref=useRef<HTMLAudioElement>(null),[blocked,setBlocked]=useState(false);useEffect(()=>{const node=ref.current!;let live=true;node.srcObject=stream;void node.play().then(()=>{if(live)setBlocked(false);}).catch(()=>{if(live)setBlocked(true);});return()=>{live=false;node.pause();node.srcObject=null;};},[stream]);return <><audio ref={ref} autoPlay/>{blocked&&<button className="voice-enable-audio" onClick={()=>void ref.current?.play().then(()=>setBlocked(false)).catch(()=>setBlocked(true))}>Enable audio for {name}</button>}</>;}
export function VoiceRoom({groupId,userId,names}:{groupId:string;userId:string;names:Record<string,string>}){
 const engine=useRef<VoiceConnection|null>(null),[open,setOpen]=useState(false),[joined,setJoined]=useState(false),[busy,setBusy]=useState(false),[muted,setMuted]=useState(true),[mode,setMode]=useState<'hold'|'open'>('hold'),[error,setError]=useState(''),[relay,setRelay]=useState(false),[members,setMembers]=useState<VoiceMember[]>([]),[remotes,setRemotes]=useState<Record<string,MediaStream>>({}),[statuses,setStatuses]=useState<Record<string,string>>({});
 const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;const mute=()=>engine.current?.mute(),hidden=()=>{if(document.hidden)mute();};window.addEventListener('blur',mute);document.addEventListener('visibilitychange',hidden);return()=>{mounted.current=false;window.removeEventListener('blur',mute);document.removeEventListener('visibilitychange',hidden);void engine.current?.stop();engine.current=null;};},[]);
 async function join(){setBusy(true);setError('');setStatuses({});const connection=new VoiceConnection(groupId,userId,{members:m=>{if(mounted.current)setMembers(m);},remote:(id,stream)=>{if(mounted.current)setRemotes(old=>{const next={...old};if(stream)next[id]=stream;else delete next[id];return next;});},status:(id,status)=>{if(mounted.current)setStatuses(old=>({...old,[id]:status}));},error:e=>{if(mounted.current)setError(e);},muted:()=>{if(mounted.current)setMuted(true);},ended:()=>{if(mounted.current){setJoined(false);setMembers([]);}}});engine.current=connection;
  try{const relay=await connection.start();if(mounted.current){setRelay(relay);setJoined(true);setMuted(true);}}catch(e){if(mounted.current){const message=typeof e==='object'&&e&&'message'in e?String(e.message):'Could not start voice.';setError(message==='VOICE_FULL'?'This room is full (four people). Try again when someone leaves.':message==='ALREADY_IN_VOICE'?'You are already in voice in another tab. Leave there first.':message);}}finally{if(mounted.current)setBusy(false);}}
 function talk(on:boolean){engine.current?.talk(on);setMuted(!on);}
 function release(){engine.current?.mute();}
 return <section className="voice-room"><button className="voice-toggle" aria-label="Voice room" title="Voice room" aria-expanded={open} onClick={()=>setOpen(!open)}>{muted?<MicrophoneSlash size={18}/>:<Microphone size={18}/>}<span>Voice room</span><small>{joined?`${members.length}/4 · ${muted?'Muted':'Microphone on'}`:'Up to four people'}</small></button>{open&&<RoomPopover className="voice-body" label="Voice room" onClose={()=>{release();setOpen(false);}}><p>Drop in together. Your microphone starts muted. Voice travels directly between participants when possible; the app does not record it.</p>{error&&<p className="auth-error" role="alert">{error}</p>}{!joined?<button className="primary-button" disabled={busy} onClick={()=>void join()}>{busy?'Opening microphone…':'Join voice'}</button>:<><div className="voice-actions"><label>Microphone mode<select aria-label="Microphone mode" value={mode} onChange={e=>{release();setMode(e.target.value as 'hold'|'open');}}><option value="hold">Push to talk</option><option value="open">Open microphone</option></select></label>{mode==='hold'?<button className={`hold-to-talk ${muted?'':'talking'}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);talk(true);}} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release} onKeyDown={e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();talk(true);}}} onKeyUp={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();release();}}} onBlur={release}>{muted?'Hold to talk':'Talking…'}</button>:<button className="primary-button" onClick={()=>talk(muted)}>{muted?'Unmute microphone':'Mute microphone'}</button>}<button className="text-button" onClick={()=>void engine.current?.stop()}><PhoneDisconnect/>Leave voice</button></div><p className="voice-connection-note">{relay?'Relay available when a direct connection is not possible.':'Direct connections only in this preview. Some networks may not connect until a relay is configured.'} Sessions end after 55 minutes; rejoin to continue.</p><ul>{members.map(m=><li key={m.session_id}><span>{names[m.user_id]||'Member'}{m.user_id===userId?' (you)':''}</span><small>{m.user_id===userId?(muted?'Muted':'Microphone on'):statuses[m.session_id]||'Connecting…'}</small></li>)}</ul></>}{busy&&<button className="text-button" onClick={()=>void engine.current?.stop()}>Cancel voice join</button>}</RoomPopover>}{Object.entries(remotes).map(([id,stream])=><RemoteAudio key={id} stream={stream} name={names[members.find(m=>m.session_id===id)?.user_id||'']||'member'}/>)}</section>;
}
