import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
type Member={user_id:string;name:string;role:string};
type Report={id:string;reporter_id:string;target_id:string;reason:string;resolved_at:string|null};
export function SafetyControls({groupId,groupName,userId,members,onChange}:{groupId:string;groupName:string;userId:string;members:Member[];onChange:()=>Promise<void>}){
 const [blocks,setBlocks]=useState<string[]>([]),[reports,setReports]=useState<Report[]>([]),[target,setTarget]=useState(''),[reason,setReason]=useState(''),[name,setName]=useState(''),[deleting,setDeleting]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const owner=members.find(m=>m.user_id===userId)?.role==='owner';
 async function load(){const [b,r]=await Promise.all([supabase!.from('member_blocks').select('blocked_id'),supabase!.from('member_reports').select('id,reporter_id,target_id,reason,resolved_at').eq('group_id',groupId).order('created_at',{ascending:false}).limit(50)]);if(b.error||r.error)throw b.error||r.error;setBlocks((b.data||[]).map(x=>x.blocked_id));setReports(r.data||[]);}
 useEffect(()=>{void load().catch(()=>setError('Could not load safety settings.'));},[groupId]);
 async function run(rpc:string,args:Record<string,unknown>,message:string):Promise<boolean>{setBusy(true);setError('');setNotice('');let saved=false;try{const r=await supabase!.rpc(rpc,args);if(r.error)throw r.error;saved=true;setNotice(message);if(rpc==='delete_group')await onChange();else await load();}catch{setError(saved?'Action saved, but the view could not refresh. Reopen Safety to check it.':'Unable to complete this action. Check your access and try again.');}finally{setBusy(false);}return saved;}
 return <div className="safety-controls"><h3>Personal blocks</h3><p>Blocking prevents private chats in every shared group and deletes your existing private conversations. Shared group messages remain visible.</p>{members.filter(m=>m.user_id!==userId).map(m=><div className="ban-row" key={m.user_id}><strong>{m.name}</strong><button disabled={busy} onClick={()=>{if(!blocks.includes(m.user_id)){setTarget(m.user_id);setReason('');return;}void run('set_member_block',{p_group_id:groupId,p_member_id:m.user_id,p_blocked:false},'Member unblocked.');}}>{blocks.includes(m.user_id)?'Unblock':'Block or report'}</button></div>)}
 {target&&<section className="safety-form"><h3>{members.find(m=>m.user_id===target)?.name}</h3><button className="danger-button" disabled={busy} onClick={()=>void run('set_member_block',{p_group_id:groupId,p_member_id:target,p_blocked:true},'Blocked. Private conversations have been deleted.').then(saved=>{if(saved)setTarget('');})}>Block and delete private chats</button><label>Report to the group owner<textarea disabled={busy} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Describe what happened…"/></label><button disabled={busy||!reason.trim()} onClick={()=>void run('report_member',{p_group_id:groupId,p_target_id:target,p_reason:reason},'Report sent to the owner.').then(saved=>{if(saved){setReason('');setTarget('');}})}>Send report</button><button onClick={()=>setTarget('')}>Cancel</button></section>}
 <h3>{owner?'Group reports':'Your reports'}</h3>{!reports.length?<p>No reports.</p>:reports.map(r=><article className="safety-report" key={r.id}><strong>{members.find(m=>m.user_id===r.target_id)?.name||'Former member'}</strong><p>{r.reason}</p><small>{r.resolved_at?'Resolved':'Open'}</small>{owner&&!r.resolved_at&&<button disabled={busy} onClick={()=>void run('resolve_report',{p_report_id:r.id},'Report marked resolved.')}>Mark resolved</button>}</article>)}
 {owner&&<><h3>Delete group</h3>{deleting?<section className="safety-form"><p>This deletes the group and its conversations for everyone. Type <strong>{groupName}</strong> to confirm.</p><input aria-label="Group name to confirm deletion" value={name} onChange={e=>setName(e.target.value)}/><button className="danger-button" disabled={busy||name!==groupName} onClick={()=>void run('delete_group',{p_group_id:groupId,p_name:name},'Group deleted.')}>Permanently delete group</button><button onClick={()=>{setDeleting(false);setName('');}}>Keep group</button></section>:<button className="danger-text" onClick={()=>setDeleting(true)}>Delete this group</button>}</>}
 {error&&<p role="alert" className="auth-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </div>;
}
