import { readSounds, soundFor } from './preferences';
let context:AudioContext|undefined;
export async function enableAudio(){if(typeof AudioContext==='undefined')throw Error('This browser does not support notification sounds. Try a browser with Web Audio support.');context??=new AudioContext();await context.resume();if(context.state!=='running')throw Error('Your browser has not enabled sound. Try again.');}
async function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('chatter-local-audio',1);r.onupgradeneeded=()=>r.result.createObjectStore('sounds');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('Local sound storage is unavailable.'));});}
async function soundBlob(key:string,value?:Blob){const db=await database();try{return await new Promise<Blob|undefined>((resolve,reject)=>{const tx=db.transaction('sounds',value?'readwrite':'readonly'),r=value?tx.objectStore('sounds').put(value,key):tx.objectStore('sounds').get(key);tx.oncomplete=()=>resolve(value||r.result);tx.onerror=()=>reject(Error('Could not store or load this sound.'));tx.onabort=()=>reject(Error('Local sound storage was interrupted.'));});}finally{db.close();}}
export async function importSound(key:string,file:File){if(file.size>2*1024*1024)throw Error('Choose an audio file under 2 MB.');await enableAudio();const decoded=await context!.decodeAudioData(await file.arrayBuffer());if(decoded.duration>5||decoded.duration<=0)throw Error('Choose a sound no longer than five seconds.');await soundBlob(key,file);}
export async function playSound(sound:string,key:string){
 if(!context||context.state!=='running'||sound==='silent')return;
 if(sound==='imported'){const blob=await soundBlob(key);if(!blob)throw Error('Import a sound for this member first.');const buffer=await context.decodeAudioData(await blob.arrayBuffer());const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);source.start();source.stop(context.currentTime+5);return;}
 const oscillator=context.createOscillator(),gain=context.createGain(),now=context.currentTime;oscillator.type='sine';oscillator.frequency.setValueAtTime(sound==='pop'?440:660,now);oscillator.frequency.exponentialRampToValueAtTime(sound==='pop'?160:880,now+.12);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.12,now+.01);gain.gain.exponentialRampToValueAtTime(.0001,now+.25);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(now);oscillator.stop(now+.26);
}
export const audioKey=(user:string,group:string,sender:string)=>`${user}:${group}:${sender}`;
export async function notifySender(user:string,group:string,sender:string){await playSound(soundFor(readSounds(user,group),sender),audioKey(user,group,sender));}
