import { createPortal } from 'react-dom';
import { useEffect, useRef, useState } from 'react';
import { Sheet } from '../groups/Sheet';
import { compileThemeCSS, defaultTheme, themeCSS, themeKey, themeSelectors, validateTheme } from './preferences';
import type { Theme } from './preferences';
import './personalization.css';
import {ThemeRuntime,validateCode,sandboxDocument} from './ThemeRuntime';
type SavedTheme={theme:Theme;css:string;code:string;enabled:boolean};

const starter=`<button onclick="parent.postMessage({type:'chatter-theme',version:1,theme:{accent:'#076371',background:'#ffffff',bubble:'#e3f2ef',text:'#243438',radius:24,fontSize:15}},'*')">Try softer bubbles</button>`;
export function ThemeSettings({userId}:{userId:string}){
 const [open,setOpen]=useState(false),[theme,setTheme]=useState<Theme>(defaultTheme),[css,setCSS]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [code,setCode]=useState(starter),[preview,setPreview]=useState('');const frame=useRef<HTMLIFrameElement>(null);
 const [enabled,setEnabled]=useState(false);const [saved,setSaved]=useState<SavedTheme>({theme:defaultTheme,css:'',code:'',enabled:false});const [previous,setPrevious]=useState<SavedTheme|null>(null);
 useEffect(()=>{try{if(new URLSearchParams(location.search).has('safe-theme')){setNotice('Safe appearance mode: saved styles and UI code are paused.');return;}const raw=localStorage.getItem(themeKey(userId));if(raw){const value=JSON.parse(raw);const t=validateTheme(value.theme);compileThemeCSS(value.css||'');setTheme(t);setCSS(value.css||'');const c=validateCode(value.code||'');setCode(c||starter);setEnabled(value.enabled===true);setSaved({theme:t,css:value.css||'',code:c,enabled:value.enabled===true});}}catch{setError('The saved theme could not be loaded. You can reset it below.');}},[userId]);
 useEffect(()=>{const node=document.createElement('style');node.dataset.chatterTheme='true';node.textContent=themeCSS(saved.theme)+compileThemeCSS(saved.css);document.head.append(node);return()=>node.remove();},[saved]);
 useEffect(()=>{function receive(e:MessageEvent){if(!open||e.source!==frame.current?.contentWindow||e.data?.type!=='chatter-theme')return;try{setTheme(validateTheme(e.data.theme));setNotice('Sandbox colors copied to preview. Apply to keep them.');}catch{setError('The sandbox sent invalid theme values.');}}window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[open]);
 function apply(){try{const next={theme:validateTheme(theme),css,code:validateCode(code),enabled};compileThemeCSS(css);localStorage.setItem(themeKey(userId),JSON.stringify(next));setPrevious(saved);setSaved(next);setNotice('Saved on this browser.');setError('');}catch(e){setError(e instanceof Error?e.message:'Could not save your theme.');}}
 const doc=sandboxDocument(preview);
 function runtimeChange(t:Theme|undefined,c:string|undefined){const next={...saved,theme:t||saved.theme,css:c??saved.css};try{localStorage.setItem(themeKey(userId),JSON.stringify(next));setSaved(next);setTheme(next.theme);setCSS(next.css);}catch{setError('Could not save the UI change.');}}
 function pause(){const next={...saved,enabled:false};setSaved(next);setEnabled(false);try{localStorage.setItem(themeKey(userId),JSON.stringify(next));}catch{setError('Code paused for this visit; browser storage is unavailable.');}}

 return <>{saved.enabled&&saved.code&&<ThemeRuntime code={saved.code} onChange={runtimeChange} onPause={pause}/>}<button className="text-button preference-launch" onClick={()=>{setOpen(true);setNotice('');}}>Appearance</button>{open&&createPortal(<Sheet label="Appearance" onClose={()=>setOpen(false)}><div className="preference-heading"><h2>Make it feel like you.</h2><button className="text-button" onClick={()=>setOpen(false)}>Done</button></div><p>Colors and code stay on this browser. Your group sees its own theme.</p>
 <div className="theme-preview" style={{background:theme.background,color:theme.text}}><small>CHAT PREVIEW</small><p style={{background:theme.bubble,borderRadius:theme.radius,fontSize:theme.fontSize}}>Same people. Your own atmosphere.</p><span style={{color:theme.accent}}>Your next conversation starts here.</span></div>
 <div className="theme-controls">{(['accent','background','bubble','text'] as const).map(key=><label key={key}>{key[0].toUpperCase()+key.slice(1)}<input type="color" value={theme[key]} onChange={e=>setTheme({...theme,[key]:e.target.value})}/></label>)}</div>
 <label>Bubble corners · {theme.radius}px<input type="range" min="0" max="32" value={theme.radius} onChange={e=>setTheme({...theme,radius:Number(e.target.value)})}/></label><label>Message size · {theme.fontSize}px<input type="range" min="12" max="20" value={theme.fontSize} onChange={e=>setTheme({...theme,fontSize:Number(e.target.value)})}/></label>
 <details className="theme-code"><summary>CSS editor</summary><p>Style {themeSelectors.join(', ')}. Optional :hover, :focus-visible and :active. Colors use hex; padding/gap 0–24px, radius 0–32px, text 12–20px. Layout: flex-direction, justify-content, text-align, line-height. Motion: transition: color 150ms ease; or animation: chatter-theme-arrive 200ms ease. Reduced motion is always respected.</p><label>Theme CSS<textarea aria-label="Theme CSS" spellCheck={false} rows={6} value={css} placeholder=".bubble { border-radius: 24px; }" onChange={e=>setCSS(e.target.value)}/></label></details>
 <details className="theme-code"><summary>Interactive code playground</summary><p>HTML and JavaScript run in an isolated frame. Enable live controls to keep them in the app after applying. They cannot read your chats or account. Send &lbrace;type: "chatter-ui", version: 1, css: ".bubble &lbrace; padding: 16px; &rbrace;"&rbrace; with parent.postMessage(..., "*") to change supported live styles. A theme object changes colors; action: "focus-composer" focuses the message field without sending.</p><label>Sandbox code<textarea aria-label="Sandbox code" spellCheck={false} rows={7} maxLength={20000} value={code} onChange={e=>setCode(e.target.value)}/></label><button className="text-button" onClick={()=>setPreview(code)}>Run preview</button><label className="sound-mute"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enable live UI controls after applying</label>{preview&&<iframe ref={frame} title="Isolated theme preview" sandbox="allow-scripts" referrerPolicy="no-referrer" srcDoc={doc}/>}</details>
 {error&&<p role="alert" className="auth-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <p><a href="?safe-theme=1">Reload with safe appearance</a> if custom code causes trouble.</p><div className="preference-actions">{previous&&<button className="text-button" onClick={()=>{try{localStorage.setItem(themeKey(userId),JSON.stringify(previous));setSaved(previous);setTheme(previous.theme);setCSS(previous.css);setCode(previous.code||starter);setEnabled(previous.enabled);setPrevious(null);setNotice('Previous appearance restored.');}catch{setError('Could not restore the previous appearance.');}}}>Roll back</button>}<button className="primary-button" onClick={apply}>Apply theme</button><button className="text-button" onClick={()=>{try{localStorage.removeItem(themeKey(userId));setTheme(defaultTheme);setCSS('');setPrevious(saved);setEnabled(false);setCode(starter);setPreview('');setSaved({theme:defaultTheme,css:'',code:'',enabled:false});setError('');setNotice('Clubhouse defaults restored.');}catch{setError('Your browser could not reset the saved theme.');}}}>Reset</button><button className="text-button" onClick={()=>{try{compileThemeCSS(css);const blob=new Blob([JSON.stringify({version:1,theme:validateTheme(theme),css,code:validateCode(code)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='apu-chatter-theme.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(String(e));}}}>Export</button><label className="theme-import">Import<input type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>150000)throw Error('Theme files must be under 150 KB.');const data=JSON.parse(await file.text());const next=validateTheme(data.theme);compileThemeCSS(data.css||'');setTheme(next);setCSS(data.css||'');setCode(validateCode(data.code||'')||starter);setEnabled(false);setError('');setNotice('Imported to preview. UI code stays off until you enable it. Apply to keep changes.');}catch(err){setError(err instanceof Error?err.message:'Could not import this file.');}}}/></label></div>
 </Sheet>,document.body)}</>;
}
