import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {compileThemeCSS,validateTheme} from './preferences';
import type {Theme} from './preferences';
export function validateCode(value:unknown):string{if(typeof value!=='string'||value.length>20000)throw Error('UI code must be text under 20,000 characters.');return value;}
export function sandboxDocument(code:string){return `<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; media-src 'none'; frame-src 'none'; form-action 'none'; base-uri 'none'"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:14px system-ui;margin:0;padding:8px;color:#243438}button{padding:9px 12px;border:0;border-radius:8px;background:#e3f2ef;color:#076371;cursor:pointer}button:focus-visible{outline:2px solid #076371;outline-offset:2px}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}</style>${validateCode(code)}`;}
export function ThemeRuntime({code,onChange,onPause}:{code:string;onChange:(theme:Theme|undefined,css:string|undefined)=>void;onPause:()=>void}){
 const frame=useRef<HTMLIFrameElement>(null),last=useRef(0),[target,setTarget]=useState<Element|null>(null),[error,setError]=useState('');
 useEffect(()=>{setTarget(document.querySelector('.connected-app > .main-area'));},[]);
 useEffect(()=>{function receive(e:MessageEvent){if(e.source!==frame.current?.contentWindow||e.origin!=='null'||!['chatter-ui','chatter-theme'].includes(e.data?.type)||e.data.version!==1||Date.now()-last.current<200)return;last.current=Date.now();try{const t=e.data.theme===undefined?undefined:validateTheme(e.data.theme),css=e.data.css===undefined?undefined:e.data.css;if(css!==undefined){if(typeof css!=='string')throw Error();compileThemeCSS(css);}if(t||css!==undefined)onChange(t,css);if(e.data.action==='focus-composer')document.querySelector<HTMLInputElement>('.connected-app > .main-area .composer input')?.focus();setError('');}catch{setError('This control sent an unsupported appearance change.');}}window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[onChange]);
 return target?createPortal(<section className="theme-runtime-shell" aria-label="Your local UI controls"><header><small>Your local UI controls</small><button className="text-button" onClick={onPause}>Pause UI code</button></header><iframe title="Your UI controls" sandbox="allow-scripts" referrerPolicy="no-referrer" ref={frame} srcDoc={sandboxDocument(code)}/>{error&&<p role="status">{error}</p>}</section>,target):null;
}
