import { PGlite } from '@electric-sql/pglite';import { readFile,readdir } from 'node:fs/promises';import assert from 'node:assert/strict';
const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb);create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert,delete on storage.objects to authenticated;create table auth.users(id uuid primary key,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);for(const f of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
const ids=Array.from({length:3},()=>crypto.randomUUID());for(const id of ids)await db.query('insert into auth.users(id,email_confirmed_at)values($1,now())',[id]);async function as(i){await db.exec('reset role');await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[ids[i]]);await db.exec('set role authenticated');}async function rpc(n,a=[]){return(await db.query(`select public.${n}(${a.map((_,i)=>'$'+(i+1)).join(',')}) as r`,a)).rows[0].r;}
await as(0);const g=await rpc('create_group',['Sharing','','UTC']),inv=await rpc('create_invite',[g]);await as(1);await rpc('join_group',[inv.token]);const p=await rpc('reserve_media',[g,'story','A memory','image/jpeg',1024]);await assert.rejects(rpc('publish_media',[p.id]));await db.exec('reset role');await db.query('insert into storage.objects(bucket_id,name,metadata)values($1,$2,$3)',['group-media',p.object_path,{size:1024,mimetype:'image/jpeg'}]);await as(1);await rpc('publish_media',[p.id]);await as(0);assert.equal((await db.query("select * from public.group_content where state='live'")).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await as(2);assert.equal((await db.query('select * from public.group_content')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);await assert.rejects(rpc('reserve_media',[g,'shared','','image/jpeg',100]));await assert.rejects(rpc('delete_content',[p.id]));
await as(1);await assert.rejects(rpc('reserve_media',[g,'shared','','text/html',100]));await assert.rejects(rpc('reserve_media',[g,'shared','','image/jpeg',2097153]));await db.exec('reset role');await db.query("update public.group_content set created_at=now()-interval '25 hours' where id=$1",[p.id]);await as(0);assert.equal((await db.query("select * from public.group_content where kind='story' and state='live'")).rows.length,1);await rpc('delete_content',[p.id]);assert.equal((await db.query('select * from storage.objects')).rows.length,0);assert.equal((await db.query("select * from public.group_content where state='live'")).rows.length,0);
await as(1);const text=await rpc('reserve_media',[g,'post','Text update',null,0]);await rpc('publish_media',[text.id]);assert.equal((await db.query("select caption from public.group_content where id=$1",[text.id])).rows[0].caption,'Text update');
await as(0);let authors=(await db.query('select * from public.group_update_authors($1)',[g])).rows;assert.equal(authors.length,1);assert.equal(authors[0].author_id,ids[1]);assert.equal(authors[0].unread,true);await rpc('mark_content_seen',[text.id]);authors=(await db.query('select * from public.group_update_authors($1)',[g])).rows;assert.equal(authors[0].unread,false);await as(2);assert.equal((await db.query('select * from public.group_update_authors($1)',[g])).rows.length,0);
await as(1);const avatar=await rpc('reserve_avatar',['image/png',100]);await assert.rejects(rpc('publish_avatar',[avatar.id]));await db.exec('reset role');await db.query('insert into storage.objects(bucket_id,name,metadata)values($1,$2,$3)',['profile-avatars',avatar.object_path,{size:100,mimetype:'image/png'}]);await as(1);await rpc('publish_avatar',[avatar.id]);await as(0);assert.equal((await db.query("select name from storage.objects where bucket_id='profile-avatars'")).rows.length,1);await as(2);assert.equal((await db.query("select name from storage.objects where bucket_id='profile-avatars'")).rows.length,0);await assert.rejects(rpc('publish_avatar',[avatar.id]));await as(1);await rpc('remove_avatar');assert.equal((await db.query("select name from storage.objects where bucket_id='profile-avatars'")).rows.length,0);await assert.rejects(rpc('reserve_avatar',['image/png',262145]));
await as(1);
for(const mime of ['image/gif','audio/webm','audio/mp4']){
 const media=await rpc('reserve_media',[g,'chat','Composer attachment',mime,100]);
 await assert.rejects(rpc('publish_media',[media.id]));
 await db.exec('reset role');await db.query('insert into storage.objects(bucket_id,name,metadata)values($1,$2,$3)',['group-media',media.object_path,{size:100,mimetype:mime}]);
 await as(1);await rpc('publish_media',[media.id]);await rpc('publish_media',[media.id]);
 assert.equal((await db.query('select id from public.group_messages where content_id=$1',[media.id])).rows.length,1);
 await as(2);assert.equal((await db.query('select id from public.group_content where id=$1',[media.id])).rows.length,0);
 await as(1);await rpc('delete_content',[media.id]);
}
await assert.rejects(rpc('reserve_media',[g,'story','','audio/webm',100]));
await assert.rejects(rpc('reserve_media',[g,'chat','','audio/webm',5242881]));
console.log('PASS: private storage, publication validation, member/outsider access, media constraints, story album retention and canonical deletion.');await db.close();
