import { useEffect,useState } from 'react';
import { ChartBar, X } from '@phosphor-icons/react';
import { supabase } from '../../lib/supabase';
import { Sheet } from '../groups/Sheet';
import './activity.css';
import {WeeklyTopics} from './WeeklyTopics';
type Activity={timezone:string;week_start:string;streak:number;today:{date:string;eligible:number;responded:number;required:number};rankings:{author_id:string;name:string;total:number;weekly:number}[];words:{word:string;count:number}[]};
export function ActivityPanel({groupId}:{groupId:string}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Activity|null>(null),[error,setError]=useState(''),[period,setPeriod]=useState<'weekly'|'total'>('weekly');
 useEffect(()=>{if(!open)return;let live=true;const load=async()=>{if(document.hidden)return;const r=await supabase!.rpc('group_activity',{p_group_id:groupId});if(!live)return;if(r.error){setData(null);setError('Unable to load activity. Check your connection and group access.');}else{setData(r.data);setError('');}};void load();const timer=setInterval(load,15000);window.addEventListener('focus',load);return()=>{live=false;clearInterval(timer);window.removeEventListener('focus',load);};},[open,groupId]);
 return <><button className="text-button activity-launch" aria-label="Activity" title="Activity" onClick={()=>setOpen(true)}><ChartBar size={17}/> Activity</button>{open&&<Sheet label="Group activity" onClose={()=>setOpen(false)}><button className="modal-close icon-btn" aria-label="Close activity" onClick={()=>setOpen(false)}><X/></button><h2>Our conversations.</h2><p>Activity inside this group. Private chats and deleted messages are excluded.</p>{error?<p role="alert">{error}</p>:!data?<p role="status">Counting conversations…</p>:<div className="activity-details"><section><h3>{data.streak} {data.streak===1?'day':'days'} together</h3><p>{data.today.responded} of {data.today.required} eligible people have chatted today.</p><progress max={data.today.required} value={data.today.responded} aria-label="Today's group streak progress"/><small>30% of {data.today.eligible} eligible members, rounded up; minimum 2. New members count from tomorrow after the first-day snapshot.</small></section><section><h3>Who’s been talking</h3><div className="activity-period"><button aria-pressed={period==='weekly'} onClick={()=>setPeriod('weekly')}>This week</button><button aria-pressed={period==='total'} onClick={()=>setPeriod('total')}>All time</button></div>{!data.rankings.length?<p>Say hello to start your group’s activity.</p>:<ol>{[...data.rankings].sort((a,b)=>b[period]-a[period]||a.name.localeCompare(b.name)).map(r=><li key={r.author_id}><span>{r.name}</span><strong>{r[period].toLocaleString()}<small> messages</small></strong></li>)}</ol>}</section><section><h3>Words this week</h3>{data.words.length?<div className="activity-words">{data.words.map(w=><span key={w.word}>{w.word} <small>{w.count}</small></span>)}</div>:<p>No common words yet.</p>}<small>English-letter words with common filler words removed.</small></section><WeeklyTopics key={groupId} groupId={groupId}/><footer>Week of {data.week_start} · {data.timezone}</footer></div>}</Sheet>}</>;
}
