import {readAlbumFolder,saveAlbumFolder} from '../groups/navigation';
import { useEffect,useRef,useState } from 'react';
import { Plus, X, Images, ArrowLeft, ArrowRight, Clock, Play, Quotes } from '@phosphor-icons/react';
import { supabase } from '../../lib/supabase';
import { Sheet } from '../groups/Sheet';
import { MediaAsset,prepareMedia } from './media';
import type { Content } from './media';
import './sharing.css';
import { contentCursor,mergeContent } from './history';
import { refreshHasGap } from '../../lib/history-gap';
export function SharingPanel({groupId,userId,role,mode,names={},authorId,onSeen,onClearAuthor}:{groupId:string;userId:string;role:string;mode:'updates'|'albums';names?:Record<string,string>;authorId?:string;onSeen?:()=>void;onClearAuthor?:()=>void}){
 const [filter,setFilter]=useState('all');
 const [items,setItems]=useState<Content[]>([]),[folder,setFolder]=useState(()=>readAlbumFolder(userId,groupId)),[composer,setComposer]=useState(false),[kind,setKind]=useState('post'),[caption,setCaption]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[opened,setOpened]=useState<Content|null>(null),[deleting,setDeleting]=useState(false);
 useEffect(()=>saveAlbumFolder(userId,groupId,folder),[userId,groupId,folder]);
 const live=useRef(true),generation=useRef(0),working=useRef(false),loaded=useRef<Content[]>([]);
 const [more,setMore]=useState(false),[paging,setPaging]=useState(false);
 async function load(append=false){
  if(working.current)return;working.current=true;const epoch=generation.current;const previous=loaded.current;
  try{
   let query=supabase!.from('group_content').select('*').eq('group_id',groupId).eq('state','live').order('created_at',{ascending:false}).order('id',{ascending:false}).limit(40);
   if(authorId)query=query.eq('author_id',authorId);
   if(mode==='updates')query=query.in('kind',['post','reel','story']).or('kind.neq.story,created_at.gt.'+new Date(Date.now()-86400000).toISOString());
   else {query=query.not('object_path','is',null);query=folder==='shared'?query.in('kind',['shared','post','reel']):query.eq('kind',folder);}
   if(append&&previous.length)query=query.or(contentCursor(previous[previous.length-1]));
   const r=await query;if(r.error)throw r.error;
   let reconciled=previous;
   if(!append&&previous.length){const current:Content[]=[];for(let i=0;i<previous.length;i+=100){const check=await supabase!.from('group_content').select('*').eq('group_id',groupId).eq('state','live').in('id',previous.slice(i,i+100).map(c=>c.id));if(check.error)throw check.error;current.push(...(check.data||[]));}reconciled=current;}
   if(!live.current||epoch!==generation.current)return;
   const incoming=r.data||[],gap=!append&&refreshHasGap(previous,incoming,40);
   const next=mergeContent(gap?[]:reconciled,incoming);loaded.current=next;setItems(next);setLoading(false);setError('');if(append||!previous.length||gap)setMore(incoming.length===40);setOpened(old=>old?next.find(c=>c.id===old.id)||null:null);
  }finally{if(epoch===generation.current)working.current=false;}
 }
 useEffect(()=>{live.current=true;generation.current++;working.current=false;loaded.current=[];setItems([]);setOpened(null);setMore(false);setLoading(true);setPaging(false);
 const refresh=()=>{if(document.hidden)return;void load().catch(()=>{if(live.current){setError('Could not refresh this group’s media. Try again.');setLoading(false);loaded.current=[];setItems([]);setOpened(null);}});};refresh();const timer=setInterval(refresh,15000);const channel=supabase!.channel('sharing:'+groupId).on('postgres_changes',{event:'*',schema:'public',table:'group_content',filter:`group_id=eq.${groupId}`},refresh).subscribe();window.addEventListener('focus',refresh);return()=>{live.current=false;generation.current++;clearInterval(timer);window.removeEventListener('focus',refresh);void supabase!.removeChannel(channel);};},[groupId,folder,mode,authorId]);
 async function publish(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');let reserved:string|undefined;try{
 const blob=file?await prepareMedia(file):null;
 if(kind!=='post'&&!blob)throw Error('Choose a photo or video for this update.');
 if(kind==='reel'&&!blob?.type.startsWith('video/'))throw Error('A reel needs a video.');
 const r=await supabase!.rpc('reserve_media',{p_group_id:groupId,p_kind:kind,p_caption:caption.trim(),p_mime:blob?.type||null,p_bytes:blob?.size||0});if(r.error)throw r.error;reserved=r.data.id;
 if(blob){const form=new FormData();form.set('contentId',r.data.id);form.set('file',blob,'media');const upload=await supabase!.functions.invoke('upload-media',{body:form});if(upload.error)throw upload.error;}
 const done=await supabase!.rpc('publish_media',{p_content_id:reserved});if(done.error)throw done.error;reserved=undefined;setComposer(false);setCaption('');setFile(null);await load();
 }catch(e){setError(e instanceof Error?e.message:typeof e==='object'&&e&&'message'in e?String(e.message):'Upload failed. Please try again.');if(reserved)await supabase!.functions.invoke('remove-content',{body:{contentId:reserved}});}finally{setBusy(false);}}
 async function remove(){if(!opened)return;setBusy(true);setError('');try{const r=await supabase!.functions.invoke('remove-content',{body:{contentId:opened.id}});if(r.error)throw r.error;setOpened(null);setDeleting(false);await load();}catch{setError('Could not finish deletion. Please try again.');}finally{setBusy(false);}}
 const visible=items.filter(c=>!authorId||c.author_id===authorId).filter(c=>mode==='updates'?['post','reel','story'].includes(c.kind)&&(c.kind!=='story'||Date.parse(c.created_at)>Date.now()-86400000):c.object_path&&(folder==='shared'?['shared','post','reel'].includes(c.kind):c.kind===folder));
 const filtered=mode==='updates'&&filter!=='all'?visible.filter(c=>c.kind===filter):visible;
 const stories=visible.filter(c=>c.kind==='story');
 const authors=[...new Set(stories.map(c=>c.author_id))];
 function openMemory(item:Content){setOpened(item);setDeleting(false);void supabase!.rpc('mark_content_seen',{p_content_id:item.id}).then(r=>{if(r.error)setError('Could not mark this update as read.');else onSeen?.();});}
 const index=opened?filtered.findIndex(c=>c.id===opened.id):-1;
 function step(direction:number){if(index<0)return;const item=filtered[index+direction];if(item)openMemory(item);}
 useEffect(()=>{if(!opened||busy||deleting)return;const handle=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();step(e.key==='ArrowLeft'?-1:1);}};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle);},[opened,busy,deleting,filtered]);
 const author=(id:string)=>id===userId?'You':names[id]||'Group member';
 return <section className={'sharing-panel '+(mode==='updates'?'stories-page':'')}>{authorId&&<button className="text-button" onClick={onClearAuthor}>Show everyone’s updates</button>}<header><div><h2>{mode==='updates'?'Life in your circle.':'Your shared memories.'}</h2><p>{mode==='updates'?'Today’s stories. The moments worth keeping.':'One place for the moments you keep together.'}</p></div><button className="primary-button" onClick={()=>{setKind(mode==='albums'?'shared':'post');setComposer(true);setError('');}}><Plus aria-hidden="true"/> {mode==='albums'?'Upload':'New update'}</button></header>
 {mode==='updates'&&<><div className="story-author-rail" aria-label="Today’s stories"><button className="story-create" onClick={()=>{setKind('story');setComposer(true);setError('');}}><span><Plus size={26} aria-hidden="true"/></span><strong>Your story</strong><small>Share today</small></button>{authors.map(id=><button className="story-author-tile" key={id} aria-label={'Open '+author(id)+' story'} onClick={()=>{setFilter('story');openMemory(stories.find(c=>c.author_id===id)!);}}><span>{author(id).slice(0,2).toUpperCase()}</span><strong>{author(id)}</strong><small>{stories.filter(c=>c.author_id===id).length} {stories.filter(c=>c.author_id===id).length===1?'moment':'moments'}</small></button>)}<div className="story-archive-note"><Clock size={23} aria-hidden="true"/><span>Here for 24 hours.<small>Kept in your Stories album.</small></span></div></div><nav className="story-filters" aria-label="Story filters">{[['all','All moments','All moments'],['story','Stories','Stories only'],['post','Posts','Posts only'],['reel','Reels','Reels only']].map(([value,label,a11y])=><button key={value} aria-label={a11y} aria-pressed={filter===value} className={filter===value?'selected':''} onClick={()=>setFilter(value)}>{label}<span>{value==='all'?visible.length:visible.filter(c=>c.kind===value).length}</span></button>)}</nav></>}
 {mode==='albums'&&<nav aria-label="Album folders">{[['shared','Shared folder'],['story','Stories'],['chat','Chat media']].map(([value,label])=><button key={value} className={folder===value?'selected':''} onClick={()=>setFolder(value)}>{label}</button>)}</nav>}{error&&<p className="auth-error" role="alert">{error}</p>}
 {loading?<div className="stories-skeleton" role="status"><span>Opening your memories…</span><i/><i/></div>:!filtered.length?<div className="sharing-empty"><Images size={36} aria-hidden="true"/><h3>{filter==='all'?'Make the first memory.':'A little space for something new.'}</h3><p>{mode==='updates'?'Share a thought, photo or short video.':'Photos and videos will appear in this folder.'}</p><button className="text-button" onClick={()=>{setKind(mode==='albums'?'shared':filter==='all'?'post':filter);setComposer(true);}}>Share a moment <Plus aria-hidden="true"/></button></div>:<div className="sharing-grid">{filtered.map((item,i)=><article className={(item.object_path?'photo-moment':'text-moment')+(i===0&&item.object_path?' featured-moment':'')} key={item.id}><div className="moment-author"><span className="moment-initials">{author(item.author_id).slice(0,2).toUpperCase()}</span><strong>{author(item.author_id)}</strong><small>{item.kind==='story'?Math.max(1,Math.ceil((Date.parse(item.created_at)+86400000-Date.now())/3600000))+'h left':new Date(item.created_at).toLocaleDateString([],{month:'short',day:'numeric'})}</small></div><div className="sharing-thumbnail">{item.object_path?<MediaAsset item={item} lazy/>:<Quotes size={30} aria-hidden="true"/>}{item.kind==='reel'&&<span className="moment-type"><Play size={13} weight="fill" aria-hidden="true"/> Reel</span>}</div><button className="sharing-open" onClick={()=>openMemory(item)}><small>{item.kind}</small><p>{item.caption||'Open this memory'}</p><span>Open update <ArrowRight aria-hidden="true" size={14}/></span></button></article>)}</div>}{more&&<button className="load-older" disabled={paging} onClick={async()=>{setPaging(true);try{await load(true);}catch{setError('Could not load older memories. Please try again.');}finally{setPaging(false);}}}>{paging?'Loading…':'Load older memories'}</button>}
 {composer&&<Sheet label="Share with your group" onClose={()=>{if(!busy)setComposer(false);}}><button className="modal-close icon-btn" aria-label="Close upload" disabled={busy} onClick={()=>setComposer(false)}><X/></button><h2>Share a little moment.</h2><p>Images up to 2 MB after compression. Videos up to 30 seconds and 15 MB.</p><form className="sharing-form" onSubmit={publish}><label>Share as<select value={kind} disabled={busy} onChange={e=>setKind(e.target.value)}>{['post','reel','story','shared','chat'].map(k=><option key={k} value={k}>{({post:'Post',reel:'Reel',story:'Story · 24 hours',shared:'Shared album',chat:'Chat photo / video'} as Record<string,string>)[k]}</option>)}</select></label><label>Caption<textarea maxLength={4000} value={caption} disabled={busy} onChange={e=>setCaption(e.target.value)}/></label><label>Photo or video<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{kind==='story'&&<p>Your story disappears from Stories after 24 hours and stays in the Stories album.</p>}{error&&<p role="alert" className="auth-error">{error}</p>}<button className="primary-button" disabled={busy||(!file&&!caption.trim())}>{busy?'Sharing…':'Share with group'}</button></form></Sheet>}
 {opened&&<Sheet label="Shared memory" onClose={()=>{if(!busy)setOpened(null);}}><button className="modal-close icon-btn" aria-label="Close memory" onClick={()=>setOpened(null)}><X/></button><div className="moment-viewer-header"><span className="moment-initials">{author(opened.author_id).slice(0,2).toUpperCase()}</span><div><h2>{author(opened.author_id)}’s moment</h2><p>{new Date(opened.created_at).toLocaleString()}</p></div></div><div className="sharing-detail"><MediaAsset item={opened}/><p>{opened.caption}</p></div><div className="moment-navigation"><button aria-label="Previous moment" disabled={busy||index<=0} onClick={()=>step(-1)}><ArrowLeft aria-hidden="true"/> Previous</button><span>{index>=0?`${index+1} / ${filtered.length}`:'Story'}</span><button aria-label="Next moment" disabled={busy||index<0||index>=filtered.length-1} onClick={()=>step(1)}>Next <ArrowRight aria-hidden="true"/></button></div>{(opened.author_id===userId||role!=='member')&&(deleting?<div><p>Delete this memory from Stories, albums and chat? This cannot be undone.</p><button className="danger-button" disabled={busy} onClick={remove}>Delete everywhere</button><button className="text-button" onClick={()=>setDeleting(false)}>Keep memory</button></div>:<button className="text-button danger-text" onClick={()=>setDeleting(true)}>Delete memory</button>)}{error&&<p role="alert">{error}</p>}</Sheet>}
 </section>;
}
